"""empty message

Revision ID: 027fff24fa0e
Revises: 5e1e89f68362
Create Date: 2022-02-05 23:12:45.062307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '027fff24fa0e'
down_revision = '5e1e89f68362'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dining_hall',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('station',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('locationId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['locationId'], ['dining_hall.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('food',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('stationId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['stationId'], ['station.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('food')
    op.drop_table('station')
    op.drop_table('dining_hall')
    # ### end Alembic commands ###
