"""empty message

Revision ID: 2b5f11c69838
Revises: d2f6a20b60bc
Create Date: 2022-02-06 01:35:30.287109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2b5f11c69838"
down_revision = "d2f6a20b60bc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_food_averate_rating"), "food", ["averate_rating"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_food_averate_rating"), table_name="food")
    # ### end Alembic commands ###
