"""empty message

Revision ID: d2f6a20b60bc
Revises: 
Create Date: 2022-02-06 01:30:11.212754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2f6a20b60bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dining_hall',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dining_hall_name'), 'dining_hall', ['name'], unique=False)
    op.create_table('station',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('locationId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['locationId'], ['dining_hall.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_station_name'), 'station', ['name'], unique=False)
    op.create_table('food',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('averate_rating', sa.Float(), nullable=False),
    sa.Column('stationId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['stationId'], ['station.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_name'), 'food', ['name'], unique=False)
    op.create_table('rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('food_rated', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['food_rated'], ['food.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rating')
    op.drop_index(op.f('ix_food_name'), table_name='food')
    op.drop_table('food')
    op.drop_index(op.f('ix_station_name'), table_name='station')
    op.drop_table('station')
    op.drop_index(op.f('ix_dining_hall_name'), table_name='dining_hall')
    op.drop_table('dining_hall')
    # ### end Alembic commands ###
